### PR TITLE
Improve `parse_token/2` and `generate_token/5`

### PR DESCRIPTION
**Pull request by sgessa**
It seems that `generate_token/5` expects a keypair, at least when the scope is `public`.
However I believe it should only need the secret key, in fact the public key is ignored.
To avoid this, it's possible to pass `{nil, sk}` or if possible, determine the public key from the secret key but it could be annoying..

Same thing goes for `parse_token/2`

Also the specs for `generate_token` only list 4 arguments but the function takes 5 arguments.

### CODE REVIEW

**Comment by sgessa** [comment]
@Ianleeclark could you please have a look? thx!

**Comment by baldarn** [comment]
interested! any updates?

**Comment by Ianleeclark** [comment]
Thank you for the PR! I just got back from vacation, but I'll try and find some time for this before Friday

**Review by Ianleeclark — APPROVED** [review]

**Comment by Ianleeclark** [comment]
Sorry for the delay, I'll get it released in a few hours!

**Pull request merged**
